### ISSUE TITLE
Key tag is not inherited from squashed struct

### ISSUE THREAD

**Issue by avorima** [rodaine/hclencoder#12]
Assuming we have the following data structures:

```go
type Foo struct {
    Name string `hcl:",key"`
    A int `hcl:"a"`
}

type Bar struct {
    Foo `hcl:",squash"`
    B int `hcl:"b"`
}

type Baz struct {
    Bar Bar `hcl:"bar"`
}
```

Encoding `Baz` will omit the `Name` field of the `Foo` struct.

**Comment by rodaine** [comment]
Thanks for the report! Feel free to submit a patch if you can figure out a fix and I'll review 😁
