### ISSUE TITLE
Data References

### ISSUE THREAD

**Issue by reneherrero** [rodaine/hclencoder#25]
Hi,

Trying to generate something like this:
```
data "vsphere_datacenter" "dc" {
  name = "dc1"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

I could do it all except the `data.vsphere_datacenter.dc.id` piece.  Am I missing something or is this simply not supported?

Thanks

**Comment by rodaine** [comment]
Howdy! This is not supported by this library.
